### ISSUE TITLE
Detect xo, standard and prettier

### ISSUE THREAD

**Issue by satazor** [IndigoUnited/node-detect-repo-linters#13]
Add detection for `xo`, `standard` and ~~`prettier`~~.

**Comment by hypescript** [comment]
I would like to add support for prettier, but the question is how should it be reflected in the linters object?
The simplest option would be to create its own category, but it doesn't seem to be very useful, cause it actually matches several existing categories, e.g. it supports both css and js, and with its support for markdown, json etc. it can arguably be classified as 'general' as well.

**Comment by satazor** [comment]
You are right.. 

Perhaps we should return an array of linter names instead of classifying them. This is a breaking change but I think it's the correct way.

What do you think?

**Comment by hypescript** [comment]
I'm afraid I can't help you with this decision, my investment in this library is rather trivial, to be honest.
Usually I'm keen to avoid breaking changes unless they are absolutely necessary, but in this case there seem to be only one dependency downstream, and you happen to be the maintainer of said dependency, so it's completely up to you, I'm fine with either option.

**Comment by satazor** [comment]
The breaking change won't affect `npms-analyzer`, so it's not a problem. Also, this breaking change will translate into a major so there's no reason to not change the API.

What I was asking was that if you agree on my proposal or if find it strange or have a better solution.

**Comment by hypescript** [comment]
Flat list of linter names is perfectly fine by me.
Please let me know how would you like to proceed with it.
I see 4 possible options (in no particular order):
1. I implement detection for prettier with the current format of the linters object as a separate category, then you change the output format.
2. I wait for you to release a new major version and then implement detection for prettier
3. I open a separate PR for the change of output format and a dependent PR to add support for prettier.
4. I open a single PR to both support prettier and change output format.

**Comment by satazor** [comment]
Go for 4. Thanks for having the time to look into this.
